In [ ]:
import numpy as np
patient_heart_rate=np.random.randint(60,101,size=(60,24)).astype(float)
missing_value=np.random.rand(60,24)<0.05
patient_heart_rate[missing_value]=np.nan

np.set_printoptions(threshold=np.inf)
print(patient_heart_rate)



[[69. 81. nan ... nan 84. 63.]
 [64. 90. 73. ... 67. 75. nan]
 [74. 86. 82. ... 71. 94. 91.]
 ...
 [76. 79. 92. ... 99. 66. 64.]
 [64. 74. 74. ... nan nan 74.]
 [62. 94. 95. ... 84. 97. 85.]]


In [ ]:
#Detect abnormal readings outside the normal range

hourly_average=np.nanmean(patient_heart_rate,axis=0)
print("Avearge heartbeat in hours")

np.set_printoptions(threshold=np.inf)
print(hourly_average)

Avearge heartbeat in hours
[82.19298246 79.70689655 80.22413793 78.66666667 78.30357143 81.61818182
 75.40677966 80.56363636 80.94117647 81.30357143 77.77966102 80.69811321
 79.74576271 77.88135593 79.39285714 79.68421053 79.01694915 80.74137931
 77.48275862 78.68421053 78.94642857 83.67241379 79.20689655 78.3220339 ]


In [18]:
#Detect abnormal readings outside the normal range

abnormal_reading=(patient_heart_rate<60)|(patient_heart_rate>90)

np.set_printoptions(threshold=np.inf)
print("Abnoramal reading")
print(abnormal_reading)

Abnoramal reading
[[ True False False False False False False  True False False False False
  False False False False False  True False False False  True False False]
 [ True False False False False  True  True False False False False False
  False False  True False  True False False False False  True False False]
 [False False False False False False False False False  True False False
  False False False False False False False False False False False False]
 [False False False False False False  True  True False  True False  True
  False False False False False False False False False False False False]
 [False  True False False False  True False False False False False False
   True False False False False False False False False  True False  True]
 [False False  True False False False  True False False False  True False
   True  True False False False False False False False  True False False]
 [ True False  True False False False False False  True False False  True
  False False 

In [19]:
#Replace missing values using forward fill logic
for i in range(patient_heart_rate.shape[0]):
    for j in range(1,patient_heart_rate.shape[1]):
        if np.isnan(patient_heart_rate[i,j]):
            patient_heart_rate[i,j]=patient_heart_rate[i,j-1]
            
for i in range(patient_heart_rate.shape[0]):
    if np.isnan(patient_heart_rate[i,0]):
        patient_heart_rate[i,0]=70
 
np.set_printoptions(threshold=np.inf)           
print(patient_heart_rate)

if np.isnan(patient_heart_rate).any():
    print("missing values")
else:
    print("no missing values")

[[ 97.  85.  86.  69.  86.  89.  60.  97.  64.  74.  80.  90.  84.  89.
   68.  64.  62.  96.  68.  66.  69.  96.  81.  62.]
 [ 93.  73.  70.  88.  70.  94.  93.  73.  73.  72.  90.  90.  84.  77.
   95.  88.  95.  65.  83.  71.  89. 100.  63.  60.]
 [ 87.  65.  86.  81.  84.  64.  64.  79.  89.  92.  83.  75.  70.  89.
   89.  62.  81.  63.  61.  65.  80.  70.  63.  66.]
 [ 87.  87.  65.  67.  84.  85.  92.  96.  68.  96.  67.  93.  73.  80.
   61.  80.  63.  81.  90.  73.  83.  76.  86.  67.]
 [ 79.  93.  62.  69.  83.  93.  86.  82.  81.  81.  73.  81.  95.  73.
   65.  72.  61.  80.  74.  69.  61. 100.  88.  93.]
 [ 82.  77.  96.  90.  73.  89.  96.  66.  66.  79.  92.  87.  99.  99.
   71.  87.  85.  62.  77.  61.  87.  96.  96.  67.]
 [ 95.  87.  95.  84.  66.  60.  62.  87.  96.  79.  71.  93.  75.  68.
   87.  95.  98.  85.  82.  75.  98.  69.  79.  72.]
 [ 84.  81.  76.  64.  80.  70.  73.  68.  69.  62.  71. 100.  86.  73.
   98.  69.  73.  70.  70.  94.  83.  78.  69.  87.]
