In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.4


In [4]:
import numpy as np
list_num=[12.23,13.32,100,36.32]
print("Original List :",list_num)
arr1=np.array(list_num)
print("One Dimensional array :",arr1)

Original List : [12.23, 13.32, 100, 36.32]
One Dimensional array : [ 12.23  13.32 100.    36.32]


In [7]:
arr2=np.array([np.arange(2,11)])
newarr=arr2.reshape(3,3)
print(newarr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
null_vector=np.zeros(10)
null_vector[6]=11
print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
