In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.19.5


In [2]:
#1.convert a list of numeric value into a one-dimensional NumPy array.
import numpy as np
list_num=[12.23,13.32,100,36.32]
print("Original List :",list_num)
arr1=np.array(list_num)
print("One Dimensional array :",arr1)

Original List : [12.23, 13.32, 100, 36.32]
One Dimensional array : [ 12.23  13.32 100.    36.32]


In [3]:
#2. 3x3 matrix with values ranging from 2 to 10.
arr2=np.array([np.arange(2,11)])
newarr=arr2.reshape(3,3)
print(newarr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
#3.Python program to create a null vector of size 10 and update sixth value to 11. 
null_vector=np.zeros(10)
null_vector[6]=11
print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
#4.Python program to reverse an array (first element becomes last). 
original_array=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
reversed_array=original_array[::-1]
print("Reverse array :",reversed_array)

Reverse array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [6]:
#5. Write a Python program to create a 2d array with 1 on the border and 0 inside.  
original_arr=np.ones((5,5))
print(original_arr)
original_arr[1:4,1:4]=0
print("output array :")
print(original_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
output array :
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
#6. Write a Python program to add a border (filled with 0's) around an existing array.  
original_ar=np.ones((3,3))
print(original_ar)
border_ar=np.zeros((5,5))
border_ar[1:4,1:4]=original_ar
print("Borderd array :")
print(border_ar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Borderd array :
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.  
checkboard_pattern=np.ones((8,8))
checkboard_pattern[0:8:2,0:8:2]=0
checkboard_pattern[1:8:2,1:8:2]=0

print("CheckBoard Pattern")
print(checkboard_pattern)

CheckBoard Pattern
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [9]:
#8. Write a Python program to convert a list and tuple into arrays.
list=[1,2,3,4,5,6,7,8]
list_to_array=np.array(list)
print("List to array")
print(list_to_array)

tuple1=(8,4,6,1,2,3)
tuple_to_array=np.array(tuple1).reshape(2,3)
print("Tuple to array")
print(tuple_to_array)


List to array
[1 2 3 4 5 6 7 8]
Tuple to array
[[8 4 6]
 [1 2 3]]


In [10]:
#9. Write a Python program to append values to the end of an array.  
original_list=[10,20,30]
original_array=np.array(original_list)
original_array=np.append(original_array,[40,50,60,70,80,90])
print(original_array)


[10 20 30 40 50 60 70 80 90]


In [11]:
#10. Write a Python program to find the real and imaginary parts of an array of complex numbers.
original_arr=np.array([ 1.00000000+0j ,0.70710678+0.70710678j])
real_part=np.real(original_arr)
img_part=np.real(original_arr)
print("original_arr")
print(original_arr)
print("Real part :")
print(real_part)
print("Imaginary part :")
print(img_part)

original_arr
[1.        +0.j         0.70710678+0.70710678j]
Real part :
[1.         0.70710678]
Imaginary part :
[1.         0.70710678]


In [12]:
#11. Write a Python program to find the number of elements of an array, length of one 
#array element in bytes and total bytes consumed by the elements.  
array=np.array([1.1,2.1,3.1])
size_of_array=array.size
length_in_bytes=array.itemsize
total_bytes_consumed=array.nbytes
print("Size of the array: ",size_of_array)
print("Length of one array element in bytes: ",length_in_bytes)  
print("Total bytes consumed by the elements of the array: ",total_bytes_consumed) 



Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [13]:
#12. Write a Python program to find common values between two arrays. 
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,8,9])
comman_value=np.intersect1d(array1,array2)
print("Array1 :",array1)
print("Array2 :",array2)
print("Comman Value between Two Array :",comman_value)

Array1 : [1 2 3 4 5]
Array2 : [2 3 8 9]
Comman Value between Two Array : [2 3]


In [14]:
#13 Write a Python program to find the set difference of two arrays.
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,8,9])
set_differnce=np.setdiff1d(array1,array2)
print("Array1 :",array1)
print("Array2 :",array2)
print("set differnce between Two Array :",set_differnce)

Array1 : [1 2 3 4 5]
Array2 : [2 3 8 9]
set differnce between Two Array : [1 4 5]


In [15]:
#14. Write a Python program to find the set exclusive-or of two arrays.
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,8,9])
set_exclusive=np.setxor1d(array1,array2)
print("Array1 :",array1)
print("Array2 :",array2)
print("set exclusive-or between Two Array :",set_exclusive)

Array1 : [1 2 3 4 5]
Array2 : [2 3 8 9]
set exclusive-or between Two Array : [1 4 5 8 9]


In [16]:
#15. Write a Python program compare two arrays using numpy.  
a=np.array([1,2])
b=np.array([4,5])
greater=np.greater(a,b)
print("a>b")
print(greater)
greater_and_equal=np.greater_equal(a,b)
print("a>=b")
print(greater_and_equal)

less=np.less(a,b)
print("a<b")
print(less)
less_and_equal=np.less_equal(a,b)
print("a<=b")
print(less_and_equal)





a>b
[False False]
a>=b
[False False]
a<b
[ True  True]
a<=b
[ True  True]


In [17]:
#15. Write a Python program to save a NumPy array to a text file.  
array=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.savetxt("numpyarray.txt",array)
np.savetxt("nparray_formate_readable.txt",array,fmt="%d")
np.savetxt("array.csv",array,delimiter=",",fmt="%d")


In [18]:
#16. Write a Python program to create a contiguous flattened array.
arr=np.array([[1,2,3],[4,5,6]])
flattend_arr=np.ravel(arr)
#flattend_arr=arr.flatten()
print(flattend_arr)

[1 2 3 4 5 6]


In [19]:
#17. Write a Python program to change the data type of an array.  
arr=np.array([[2,4,6],[6,8,10]])
print(arr)
print(arr.dtype)
new_arr=arr.astype(float)
print(new_arr.dtype)
print(new_arr)


[[ 2  4  6]
 [ 6  8 10]]
int32
float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [20]:
arr=np.array([[2,4,6],[6,8,10]],dtype=float)
print(arr)
print(arr.dtype)


[[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


In [21]:
#18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#19. Write a Python program to create an array which looks like below array.  
arr=np.zeros((4,3))
arr[1:,:]=np.tril(np.ones((3,3)))
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [23]:
#20. Write a Python program to concatenate two 2-dimensional arrays.
arr1=np.array([[0,1,3],[5,7,9]])
arr2=np.array([[0,2,4],[6,8,10]])
print(np.concatenate((arr1,arr2),axis=1))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [24]:
#21. Write a Python program to make an array immutable (read-only).
arr=np.array([1,2,3,4,5,6])
arr.flags.writeable=False
arr[0]=10


ValueError: assignment destination is read-only

In [ ]:
#22. Write a Python program to create an array of (3, 4) shape, multiply every element 
#value by 3 and display the new array.
arr=np.arange(12).reshape(3,4)
print("original array :")
print(arr)
print("New Array Elements :")
print(arr*3)

original array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array Elements :
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [ ]:
#23. Write a Python program to convert a NumPy array into Python list structure.
print("original array")
arr=np.arange(6).reshape(3,2)
print(arr)
arr_to_list=arr.tolist()
print("Array to list")
print(arr_to_list)

original array
[[0 1]
 [2 3]
 [4 5]]
Array to list
[[0, 1], [2, 3], [4, 5]]


In [ ]:
#24. Write a Python program to print precision
arr=np.array([ 0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349, 
0.35399976,0.99469633,0.0694458,0.54711478])
print("original array elements:")
print(arr)

print("Array Value with precision 3 :")
print(np.round(arr,3))

original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Array Value with precision 3 :
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [ ]:
#25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.
arr=np.array([1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])


print("array values with precision 3:  ")
np.set_printoptions(suppress=True,precision=3)
print(arr)

array values with precision 3:  
[   0.       1.6   1200.       0.235]


In [ ]:
#26. Write a Python program to how to add an extra column to an numpy array.
print("original array")
arr=np.arange(10,70,10).reshape(2,3)
print(arr)
new_colum=np.array([100,200])

new_arr=np.column_stack((arr,new_colum))
print(new_arr)

original array
[[10 20 30]
 [40 50 60]]
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [ ]:
print("Original array: ")
arr=np.arange(10,110,10)
print(arr)
print("Delete first, fourth and fifth elements: ")
new_arr=np.delete(arr,[0,3,4])
print(new_arr)

Original array: 
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements: 
[ 20  30  60  70  80  90 100]
